# Generated by Django 5.0.4 on 2024-04-11 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_remove_book_tags_book_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='tags',
            new_name='tag',
        ),
    ]
